
services:
  hdt-converter:
    image: rdfhdt/hdt-java
    volumes:
      - ../datasets:/datasets
      - ./convert-and-hdt.sh:/convert-and-hdt.sh
    entrypoint: ["bash", "-c", "/convert-and-hdt.sh"]
    environment:
      JAVA_OPTIONS: "-Xmx20g"
      DATASET_1: "ChEBI"          #   4772706 triples
      DATASET_2: "DBPedia-Subset" #  42849609 triples
      DATASET_3: "DrugBank"       #    517023 triples
      DATASET_4: "GeoNames"       # 107950085 triples
      DATASET_5: "Jamendo"        #   1049647 triples
      DATASET_6: "KEGG"           #   1090830 triples
      DATASET_7: "LMDB"           #   6147996 triples
      DATASET_8: "NYT"            #    335197 triples
      DATASET_9: "SP2B"           #  10000457 triples
      DATASET_10: "SWDFood"       #    103595 triples

